### ISSUE TITLE
How to configure Docker to relay mail via Gmail Smtp?

### ISSUE THREAD

**Issue by wittawatu** [iwayvietnam/zimbra-docker#2]
Hi,
   I'm running home server using Public DHCP and using DDNS with No-IP, sending email out from my dynamic IP sometime the msg is going to JUNK,
   Please assist

**Comment by tuanta** [comment]
After run a new container, you can login to Zimbra Admin Console or to command line to configure this as normally.

Spam/Junk is a different issue. You should refer to Spam filter guides.

**Comment by wittawatu** [comment]
Thank you
